server:
  port: 8090
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8085/eureka/


spring:
  cloud:
    discovery:
      enable: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microservice-credits
          uri: lb://microservice-credits
          predicates:
            - Path=/credits/**