server:
  port: 8090

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8088/eureka/


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microservice-credits
          uri: lb://microservice-credits
          predicates:
            - Path=/credits/**
        - id: microservice-accounts
          uri: lb://microservice-accounts
          predicates:
            - Path=/savings-accounts/**,/current-accounts/**,/fixedterm-accounts/**
        - id: microservice-customers
          uri: lb://microservice-customers
          predicates:
            - Path=/personal-customers/**,/business-customers/**
