account:
  property: Accounts Profile Dev
server:
  port: 8081

spring:
  application:
    name: microservice-accounts
  data:
    mongodb:
      uri:  mongodb+srv://useraccount:passaccount@clusterconexion.j8gyv.mongodb.net/?retryWrites=true&w=majority
      database: accountsBD


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8085/eureka
    instance:
      hostname: localhost

#account.property= Accounts Profile Dev
#spring.application.name=microservice-accounts
#server.port=8081
#spring.data.mongodb.uri=mongodb+srv://useraccount:passaccount@clusterconexion.j8gyv.mongodb.net/?retryWrites=true&w=majority
#spring.data.mongodb.database=accountsBD

#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.client.service-url.default-zone=http://localhost:8085/eureka
#eureka.client.instance.hostname=localhost