#customer.property= Customer Profile Dev
#spring.application.name=microservice-customers
#server.port=8082
#spring.data.mongodb.uri=mongodb+srv://usercustomer:passcustomer@clusterconexion.j8gyv.mongodb.net/?retryWrites=true&w=majority
#spring.data.mongodb.database=customersBD


#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.client.service-url.default-zone=http://localhost:8085/eureka
#eureka.client.instance.hostname=localhost


customers:
  property: Customers Profile Dev
server:
  port: 8082
  #${PORT:${SERVER_PORT:0}}
#8082

spring:
  application:
    name: microservice-customers
  data:
    mongodb:
      uri:  mongodb+srv://usercustomer:passcustomer@clusterconexion.j8gyv.mongodb.net/?retryWrites=true&w=majority
      database: customersBD

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}