#credit.property= Credits Profile Dev
#spring.application.name=microservice-credits
#server.port=8083
#spring.data.mongodb.uri=mongodb+srv://usercredit:passcredit@clusterconexion.j8gyv.mongodb.net/?retryWrites=true&w=majority
#spring.data.mongodb.database=creditsBD

#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#eureka.client.service-url.default-zone=http://localhost:8085/eureka
#eureka.client.instance.hostname=localhost

account:
  property: Credits Profile Dev
server:
  port: ${PORT:${SERVER_PORT:0}}
#8083

spring:
  application:
    name: microservice-credits
  data:
    mongodb:
      uri:  mongodb+srv://usercredit:passcredit@clusterconexion.j8gyv.mongodb.net/?retryWrites=true&w=majority
      database: creditsBD

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}